{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "livy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "livy.name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["*"]
- apiGroups: ["", "extensions"]
  resources: ["configmaps", "services", "ingresses"]
  verbs: ["create", "update", "get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["", "rbac.authorization.k8s.io"]
  resources: ["serviceaccounts", "rolebindings"]
  verbs: ["create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "livy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "livy.name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "livy.fullname" . }}
subjects:
- name: {{ template "livy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "livy.fullname" . }}-spark
  labels:
    app.kubernetes.io/name: {{ include "livy.name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "livy.fullname" . }}-spark
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "livy.name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "livy.fullname" . }}-spark
subjects:
- name: {{ template "livy.sparkServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
{{- end -}}
