apiVersion: v1
appVersion: v0.7.0-incubating
description: Apache Livy on Kubernetes
home: https://livy.incubator.apache.org/
icon: https://livy.incubator.apache.org/assets/themes/apache/img/logo.png
keywords:
- livy
- spark
maintainers:
- email: jahstreetlove@gmail.com
  name: Aliaksandr Sasnouskikh
name: livy
version: 0.3.0
sources:
  - https://github.com/jahstreet/incubator-livy/tree/v0.6.0-incubating-kubernetes-support