apiVersion: v1
appVersion: "2.4.5"
description: Spark cluster with Livy and JupyterHub atop Kubernetes
keywords:
- livy
- spark
- jupyterhub
- history-server
maintainers:
- email: jahstreetlove@gmail.com
  name: Aliaksandr Sasnouskikh
name: spark-cluster
version: 0.8.0