apiVersion: v1
name: spark-cluster
version: 2.0.0
appVersion: 3.0.1
home: https://github.com/jahstreet/spark-on-kubernetes-helm
description: Spark cluster with Livy and JupyterHub on Kubernetes
keywords:
- livy
- spark
- jupyterhub
- history-server
sources:
  - https://github.com/jahstreet/spark-on-kubernetes-helm
  - https://github.com/jahstreet/spark-on-kubernetes-docker
  - https://github.com/apache/incubator-livy/pull/167
maintainers:
- name: jahstreet
  email: jahstreetlove@gmail.com
kubeVersion: 1.11.0 - 1.18.9
